### ISSUE TITLE
💬 [Question] Use Of 'SMTP_SECURE'

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social-Deploy-Rebranding#13]
## 💬 Question

The Helm backend value `SMTP_SECURE` seems not to be used in the ocelot.social backend.
Instead it is derived from `SMTP_IGNORE_TLS`, see here:
https://github.com/Ocelot-Social-Community/Ocelot-Social/blob/6773633282e6c5e1b8faf571a27456350ccdcdc2/backend/src/config/index.js#L44

What we will do about this @ulfgebhardt ?

- Is it a bug?
- Or should we use it?

**Comment by ulfgebhardt** [comment]
![image](https://user-images.githubusercontent.com/1238238/120777519-aa816280-c525-11eb-83a8-44389c204807.png)

it is an option in nodemailer which can be set

**Comment by ulfgebhardt** [comment]
the code part you reference seem to be an error tho
