### ISSUE TITLE
💥 [DevOps] Shall `AppVersion` In `deployment/kubernetes/Chart.yaml` Be Really `latest`

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social-Deploy-Rebranding#47]
## 💥 DevOps

Shall `AppVersion` in `deployment/kubernetes/Chart.yaml` be really `latest`?

### Todo

- [ ] shall `AppVersion` in `deployment/kubernetes/Chart.yaml` be really `latest` or better the actual explicit version?
  - if a pod restarts it may pull a wrong docker image that is to new
    - warnings against using `latest`:
      - see https://stackoverflow.com/questions/33112789/how-do-i-force-kubernetes-to-re-pull-an-image
- [ ] if not possible then mention it in the docs !!!

**Comment by ulfgebhardt** [comment]
fixed
